### ISSUE TITLE
GitHub Kanban Project review

### ISSUE THREAD

**Issue by betses** [betses/JavaScript-group-capstone#21]
### Project link https://github.com/betses/JavaScript-group-capstone/projects/1
There are 2 people in this project @Haadiiii and @betses.

Please kindly review our GitHub project kanban board.
Regards

**Comment by zhadier** [comment]
## Hi @betses & @Haadiiii  👋  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media2.giphy.com/media/ByeYxURXxPyptxD2ta/giphy-downsized-medium.gif"/>

# Congratulations! 🎉 

✔️ Great job implementing the Kanban

### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
